# Generated by Django 3.1.4 on 2023-04-04 07:50

import curriculum_tracking.models
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('curriculum_tracking', '0023_delete_contentitemautomarkerconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItemAutoMarkerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('debug', 'debug'), ('prod', 'prod'), ('deactivated', 'deactivated')], max_length=11)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automarker_configs', to='curriculum_tracking.contentitem')),
                ('flavours', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            bases=(models.Model, curriculum_tracking.models.FlavourMixin, curriculum_tracking.models.ContentItemProxyMixin),
        ),
    ]
