# Generated by Django 3.1.4 on 2021-07-20 16:21

from django.db import migrations, models
import django.db.models.deletion
import model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            bases=(models.Model, model_mixins.Mixins),
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('datatype', models.CharField(choices=[('i', 'integer'), ('s', 'string'), ('b', 'boolean')], max_length=1)),
                ('repeated', models.BooleanField()),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.namespace')),
            ],
            bases=(models.Model, model_mixins.Mixins),
        ),
    ]
