# Generated by Django 3.1.4 on 2021-11-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
