# Generated by Django 3.1.4 on 2021-12-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20211103_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
