# Generated by Django 3.1.4 on 2023-03-09 10:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20230309_0838'),
        ('zero_marginal_cost_challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengeregistration',
            unique_together={('user', 'curriculum')},
        ),
    ]
