import {
  fillInSnapshotDateGaps,
  removeDuplicateDates,
  addEventColorsToLogEntries,
} from "./utils";
test("fillInSnapshotDateGaps returns updated burnDownSnapshots with gap dates filled", () => {
  const burnDownSnapshots = [
    {
      timestamp: "2022-04-10",
      total: 5,
    },
    {
      timestamp: "2022-04-15",
      total: 10,
    },
    {
      timestamp: "2022-04-16",
      total: 15,
    },
    {
      timestamp: "2022-04-17",
      total: 20,
    },
    {
      timestamp: "2022-04-18",
      total: 25,
    },
    {
      timestamp: "2022-04-19",
      total: 30,
    },
  ];
  const sampleUpdatedBurnDownSnapshots = [
    {
      timestamp: "2022-04-10",
      total: 5,
    },
    {
      timestamp: "2022-04-11",
      total: 5,
    },
    {
      timestamp: "2022-04-12",
      total: 5,
    },
    {
      timestamp: "2022-04-13",
      total: 5,
    },
    {
      timestamp: "2022-04-14",
      total: 5,
    },
    {
      timestamp: "2022-04-15",
      total: 10,
    },
    {
      timestamp: "2022-04-16",
      total: 15,
    },
    {
      timestamp: "2022-04-17",
      total: 20,
    },
    {
      timestamp: "2022-04-18",
      total: 25,
    },
    {
      timestamp: "2022-04-19",
      total: 30,
    },
  ];
  const result = fillInSnapshotDateGaps({ burnDownSnapshots });
  expect(result).toEqual(sampleUpdatedBurnDownSnapshots);
});

test("removeDuplicateDates returns updated burnDownSnapshots with duplicate dates removed", () => {
  const burnDownSnapshots = [
    {
      timestamp: "2022-04-10",
      total: 5,
    },
    {
      timestamp: "2022-04-15",
      total: 10,
    },
    {
      timestamp: "2022-04-16",
      total: 15,
    },
    {
      timestamp: "2022-04-17",
      total: 20,
    },
    {
      timestamp: "2022-04-18",
      total: 25,
    },
    {
      timestamp: "2022-04-19",
      total: 35,
    },
    {
      timestamp: "2022-04-19",
      total: 35,
    },
  ];
  const sampleUpdatedBurnDownSnapshots = [
    {
      timestamp: "2022-04-10",
      total: 5,
    },
    {
      timestamp: "2022-04-15",
      total: 10,
    },
    {
      timestamp: "2022-04-16",
      total: 15,
    },
    {
      timestamp: "2022-04-17",
      total: 20,
    },
    {
      timestamp: "2022-04-18",
      total: 25,
    },
    {
      timestamp: "2022-04-19",
      total: 35,
    },
  ];
  const result = removeDuplicateDates({ burnDownSnapshots });
  expect(result).toEqual(sampleUpdatedBurnDownSnapshots);
});

test("fillInSnapshotDateGaps does not error when burnDownSnapshots is an empty array", () => {
  const burnDownSnapshots = [];
  const result = fillInSnapshotDateGaps({ burnDownSnapshots });
  expect(result).toEqual([]);
});

test("", () => {
  const eventTypes = {
    id: 2,
    name: "CARD_REVIEW_REQUESTED",
    description: null,
  };
  const eventTypeColors = {
    CARD_MOVED_TO_COMPLETE: "#fdd835",
    CARD_MOVED_TO_REVIEW_FEEDBACK: "#e53935",
    CARD_REVIEW_REQUESTED: "#fb8c00",
    CARD_REVIEW_REQUEST_CANCELLED: "#757575",
    CARD_STARTED: "#43a047",
    PR_REVIEWED: "#8e24aa",
    COMPETENCE_REVIEW_DONE: "#1e88e5",
  };
  const activityLogEntries = {
    129: {
      id: 129,
      timestamp: "2022-10-06T09:07:03.401226Z",
      eventType: 2,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic progress",
      object1Id: 16,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: null,
    },
    130: {
      id: 130,
      timestamp: "2022-10-06T10:16:48.005745Z",
      eventType: 4,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic review",
      object1Id: 5,
      object2ContentTypeName: "curriculum_tracking | topic progress",
      object2Id: 16,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
    },
    131: {
      id: 131,
      timestamp: "2022-10-06T10:16:48.063210Z",
      eventType: 6,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic progress",
      object1Id: 16,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: null,
    },
    132: {
      id: 132,
      timestamp: "2022-10-06T11:52:12.708062Z",
      eventType: 2,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic progress",
      object1Id: 16,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: null,
    },
    133: {
      id: 133,
      timestamp: "2022-10-06T11:52:19.663708Z",
      eventType: 4,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic review",
      object1Id: 6,
      object2ContentTypeName: "curriculum_tracking | topic progress",
      object2Id: 16,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
    },
    134: {
      id: 134,
      timestamp: "2022-10-06T11:52:19.733146Z",
      eventType: 6,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic progress",
      object1Id: 16,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: null,
    },
    135: {
      id: 135,
      timestamp: "2022-10-06T11:52:26.259367Z",
      eventType: 3,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic progress",
      object1Id: 16,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: null,
    },
    136: {
      id: 136,
      timestamp: "2022-10-06T12:30:13.626446Z",
      eventType: 2,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic progress",
      object1Id: 16,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: null,
    },
    137: {
      id: 137,
      timestamp: "2022-10-12T08:31:32.819526Z",
      eventType: 3,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic progress",
      object1Id: 16,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: null,
    },
    138: {
      id: 138,
      timestamp: "2022-10-12T11:52:20.061481Z",
      eventType: 1,
      actorUser: 18,
      effectedUser: 5,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "learner_a_3@email.com",
      object1ContentTypeName: "curriculum_tracking | recruit project",
      object1Id: 7,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        card: 27,
        title: "Tilde project tutorial: How to submit a link",
        flavourNames: [],
      },
      object2Summary: null,
    },
    139: {
      id: 139,
      timestamp: "2022-10-12T11:52:21.866156Z",
      eventType: 2,
      actorUser: 18,
      effectedUser: 5,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "learner_a_3@email.com",
      object1ContentTypeName: "curriculum_tracking | recruit project",
      object1Id: 7,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        card: 27,
        title: "Tilde project tutorial: How to submit a link",
        flavourNames: [],
      },
      object2Summary: null,
    },
    140: {
      id: 140,
      timestamp: "2022-10-12T11:52:32.042440Z",
      eventType: 4,
      actorUser: 18,
      effectedUser: 5,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "learner_a_3@email.com",
      object1ContentTypeName: "curriculum_tracking | recruit project review",
      object1Id: 37,
      object2ContentTypeName: "curriculum_tracking | recruit project",
      object2Id: 7,
      object1Summary: {
        recruitProject: 7,
        card: 27,
        title: "Tilde project tutorial: How to submit a link",
        flavourNames: [],
      },
      object2Summary: {
        card: 27,
        title: "Tilde project tutorial: How to submit a link",
        flavourNames: [],
      },
    },
    141: {
      id: 141,
      timestamp: "2022-10-12T11:52:32.114303Z",
      eventType: 6,
      actorUser: 18,
      effectedUser: 5,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "learner_a_3@email.com",
      object1ContentTypeName: "curriculum_tracking | recruit project",
      object1Id: 7,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        card: 27,
        title: "Tilde project tutorial: How to submit a link",
        flavourNames: [],
      },
      object2Summary: null,
    },
    145: {
      id: 145,
      timestamp: "2022-10-12T18:06:50.225433Z",
      eventType: 4,
      actorUser: 18,
      effectedUser: 17,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "someone.nice@example.com",
      object1ContentTypeName: "curriculum_tracking | recruit project review",
      object1Id: 38,
      object2ContentTypeName: "curriculum_tracking | recruit project",
      object2Id: 8,
      object1Summary: {
        recruitProject: 8,
        card: 82,
        title: "Tilde project tutorial: How to submit a link",
        flavourNames: [],
      },
      object2Summary: {
        card: 82,
        title: "Tilde project tutorial: How to submit a link",
        flavourNames: [],
      },
    },
    146: {
      id: 146,
      timestamp: "2022-10-12T18:06:50.327771Z",
      eventType: 6,
      actorUser: 18,
      effectedUser: 17,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "someone.nice@example.com",
      object1ContentTypeName: "curriculum_tracking | recruit project",
      object1Id: 8,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        card: 82,
        title: "Tilde project tutorial: How to submit a link",
        flavourNames: [],
      },
      object2Summary: null,
    },
    147: {
      id: 147,
      timestamp: "2022-10-19T09:07:00.617977Z",
      eventType: 2,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic progress",
      object1Id: 16,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: null,
    },
    148: {
      id: 148,
      timestamp: "2022-10-19T09:09:00.040482Z",
      eventType: 4,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic review",
      object1Id: 7,
      object2ContentTypeName: "curriculum_tracking | topic progress",
      object2Id: 16,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
    },
    149: {
      id: 149,
      timestamp: "2022-10-19T09:09:00.129872Z",
      eventType: 6,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic progress",
      object1Id: 16,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: null,
    },
    150: {
      id: 150,
      timestamp: "2022-10-19T10:44:29.651533Z",
      eventType: 2,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic progress",
      object1Id: 16,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: null,
    },
    151: {
      id: 151,
      timestamp: "2022-10-19T10:44:31.910454Z",
      eventType: 3,
      actorUser: 18,
      effectedUser: 18,
      actorUserEmail: "faith.mofokeng@umuzi.org",
      effectedUserEmail: "faith.mofokeng@umuzi.org",
      object1ContentTypeName: "curriculum_tracking | topic progress",
      object1Id: 16,
      object2ContentTypeName: null,
      object2Id: null,
      object1Summary: {
        topicProgress: 16,
        card: 76,
        title: "Understanding the review column",
        flavourNames: [],
      },
      object2Summary: null,
    },
  };
  const newData = {
    id: 139,
    timestamp: "2022-10-12T11:52:21.866156Z",
    eventType: 2,
    actorUser: 18,
    effectedUser: 5,
    actorUserEmail: "faith.mofokeng@umuzi.org",
    effectedUserEmail: "learner_a_3@email.com",
    object1ContentTypeName: "curriculum_tracking | recruit project",
    object1Id: 7,
    object2ContentTypeName: null,
    object2Id: null,
    object1Summary: {
      card: 27,
      title: "Tilde project tutorial: How to submit a link",
      flavourNames: [],
    },
    object2Summary: null,
    eventName: "CARD_REVIEW_REQUESTED",
    eventColor: "#fb8c00",
  };
  expect(
    addEventColorsToLogEntries({
      eventTypes,
      eventTypeColors,
      activityLogEntries,
    })
  ).toEqual(newData);
});
