# https://github.com/casey/just
INSTALLER := if `uname -s` == "Darwin" { "brew" } else { "sudo apt" }

setup_graphing:
	@if [[ "`uname -s`" == "Darwin" ]]; \
		then echo "installing for osx" && brew install graphviz; \
		else echo "installing for linux" && sudo apt install python3.9-dev graphviz graphviz-dev; \
	fi
	pipenv install -d
	-mkdir gitignore
