# same as prod 

apiVersion: v1
kind: Service
metadata:
  name: automarker
  labels:
    app: automarker
#   namespace: default
spec:
  ports:
    - port: 80
      #   protocol: TCP
      targetPort: 1337
  selector:
    app: automarker
  type: ClusterIP


