# Generated by Django 3.1.4 on 2024-03-11 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum_tracking', '0025_remove_contentitem_topic_needs_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReviewBundleClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_timestamp', models.DateTimeField(auto_now_add=True)),
                ('due_timestamp', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('claimed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projects_reviewed', models.ManyToManyField(related_name='project_review_bundle_claims_reviewed', to='curriculum_tracking.RecruitProject')),
                ('projects_someone_else_got_to', models.ManyToManyField(to='curriculum_tracking.RecruitProject')),
                ('projects_to_review', models.ManyToManyField(related_name='project_review_bundle_claims', to='curriculum_tracking.RecruitProject')),
            ],
        ),
    ]
