# Generated by Django 3.1.4 on 2021-12-24 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='effected_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='log_entries_as_effected_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
