version: "3.3"
services:
  automarker:
    # image: gcr.io/umuzi-prod/automarker:latest
    build: .
    restart: always
    ports:
      - "1337:1337"
    volumes:
      - ~/.ssh:/root/.ssh
      - $AUTO_MARKER_CONFIGURATION_REPO_PATH:/home/node/app/project_config
