# Generated by Django 3.1.4 on 2021-04-08 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('git_real', '0002_auto_20200528_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='git_real.repository'),
        ),
    ]
