# Generated by Django 3.1.4 on 2021-04-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_real', '0003_auto_20210408_0506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repository', 'number')},
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='assignees',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='user',
        ),
    ]
