# Generated by Django 3.1.4 on 2021-05-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_real', '0004_auto_20210419_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pullrequestreview',
            name='number',
        ),
        migrations.AddField(
            model_name='pullrequestreview',
            name='html_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
