# Generated by Django 3.1.4 on 2022-09-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_real', '0008_auto_20220922_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequestreview',
            name='validated',
            field=models.CharField(blank=True, choices=[('d', 'contradicted')], max_length=1, null=True),
        ),
    ]
