# followed this guide: https://sweetcode.io/set-up-telegraf-influxdb-and-grafana-with-docker-compose/

version: "3.3"
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./gitignore/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=locust
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      # - INFLUXDB_USER=telegraf
      # - INFLUXDB_USER_PASSWORD=secretpassword 
      
  grafana:
   image: grafana/grafana
   container_name: grafana-server
   restart: always
   depends_on:
     - influxdb
   environment:
     - GF_SECURITY_ADMIN_USER=admin
     - GF_SECURITY_ADMIN_PASSWORD=admin
     - GF_INSTALL_PLUGINS=
   links:
     - influxdb
   ports:
     - '3000:3000'
   volumes:
     - ./gitignore/grafana_data:/var/lib/grafana