# Generated by Django 2.1.5 on 2020-05-28 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitproject',
            name='review_request_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitprojectreview',
            name='trusted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruitproject',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruit_projects', to='git_real.Repository'),
        ),
        migrations.AlterField(
            model_name='recruitproject',
            name='reviewer_users',
            field=models.ManyToManyField(blank=True, default=list, related_name='projects_to_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
