# Generated by Django 2.1.5 on 2020-06-03 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum_tracking', '0002_auto_20200528_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum_tracking.ContentItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, model_mixins.Mixins),
        ),
        migrations.CreateModel(
            name='WorkshpAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('attendee_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum_tracking.ContentItem')),
            ],
            bases=(models.Model, model_mixins.Mixins),
        ),
        migrations.AlterField(
            model_name='agilecard',
            name='recruit_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agile_card', to='curriculum_tracking.RecruitProject', unique=True),
        ),
        migrations.AddField(
            model_name='agilecard',
            name='topic_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agile_card', to='curriculum_tracking.TopicProgress', unique=True),
        ),
        migrations.AddField(
            model_name='agilecard',
            name='workshop_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agile_card', to='curriculum_tracking.WorkshpAttendance', unique=True),
        ),
    ]
