# Generated by Django 2.1.5 on 2020-06-09 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200609_1130'),
        ('curriculum_tracking', '0004_auto_20200603_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('suppress_card_generation', models.BooleanField(default=False)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Curriculum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
