# Generated by Django 2.1.5 on 2020-07-01 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_tracking', '0005_courseregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseregistration',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agilecard',
            name='recruit_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agile_card', to='curriculum_tracking.RecruitProject'),
        ),
        migrations.AlterField(
            model_name='agilecard',
            name='topic_progress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agile_card', to='curriculum_tracking.TopicProgress'),
        ),
        migrations.AlterField(
            model_name='agilecard',
            name='workshop_attendance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agile_card', to='curriculum_tracking.WorkshopAttendance'),
        ),
    ]
