# Generated by Django 2.1.5 on 2020-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_tracking', '0006_auto_20200701_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitproject',
            name='code_review_competent_since_last_review_request',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruitproject',
            name='code_review_excellent_since_last_review_request',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruitproject',
            name='code_review_ny_competent_since_last_review_request',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruitproject',
            name='code_review_red_flag_since_last_review_request',
            field=models.IntegerField(default=0),
        ),
    ]
