# Generated by Django 2.1.5 on 2020-08-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_tracking', '0009_auto_20200804_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitproject',
            old_name='review_request_timestamp',
            new_name='review_request_time',
        ),
        migrations.AddField(
            model_name='recruitproject',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
