# Generated by Django 2.1.5 on 2020-09-20 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum_tracking', '0010_auto_20200828_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NYC', 'not yet competent'), ('C', 'competent'), ('E', 'excellent'), ('R', 'red flag')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, model_mixins.Mixins),
        ),
        migrations.RenameField(
            model_name='recruitproject',
            old_name='submission_time',
            new_name='complete_time',
        ),
        migrations.RenameField(
            model_name='topicprogress',
            old_name='end_time',
            new_name='complete_time',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='link_regex',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='recruitproject',
            name='link_submission',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='review_request_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitprojectreview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topicprogress',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicreview',
            name='topic_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_reviews', to='curriculum_tracking.TopicProgress'),
        ),
    ]
