# Generated by Django 3.1.4 on 2021-02-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_tracking', '0012_auto_20210121_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitprojectreview',
            name='validated',
            field=models.CharField(blank=True, choices=[('i', 'incorrect'), ('c', 'correct'), ('d', 'contradicted')], max_length=1, null=True),
        ),
    ]
