# Generated by Django 3.1.4 on 2021-04-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_tracking', '0013_recruitprojectreview_validated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recruitproject',
            unique_together=set(),
        ),
    ]
