# Generated by Django 3.1.4 on 2021-07-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_tracking', '0014_auto_20210408_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitproject',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='curriculum_tracking.contentitem'),
        ),
    ]
