# Generated by Django 3.1.4 on 2021-10-18 09:43

from django.db import migrations, models
import model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_tracking', '0015_auto_20210720_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            bases=(models.Model, model_mixins.Mixins),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='learning_outcomes',
            field=models.ManyToManyField(blank=True, related_name='content_items', to='curriculum_tracking.LearningOutcome'),
        ),
    ]
