# Generated by Django 3.1.4 on 2021-11-10 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum_tracking', '0016_auto_20211018_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurndownSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cards_total_count', models.SmallIntegerField()),
                ('project_cards_total_count', models.SmallIntegerField()),
                ('cards_in_complete_column_total_count', models.SmallIntegerField()),
                ('project_cards_in_complete_column_total_count', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
