# Generated by Django 3.1.4 on 2022-08-09 09:44

import curriculum_tracking.models
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('curriculum_tracking', '0018_contentitem_protect_main_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='story_points',
        ),
        migrations.CreateModel(
            name='ContentItemAutoMarkerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_marker_when_card_in_review', models.BooleanField(default=False)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automarker_configs', to='curriculum_tracking.contentitem')),
                ('flavours', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            bases=(models.Model, curriculum_tracking.models.FlavourMixin, curriculum_tracking.models.ContentItemProxyMixin),
        ),
        migrations.CreateModel(
            name='ContentItemAgileWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agile_weights', to='curriculum_tracking.contentitem')),
                ('flavours', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            bases=(models.Model, curriculum_tracking.models.FlavourMixin, curriculum_tracking.models.ContentItemProxyMixin),
        ),
    ]
