# Generated by Django 3.1.4 on 2023-03-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_tracking', '0020_recruitprojectreview_complete_review_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='link_example',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='link_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='link_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
