# Generated by Django 3.1.4 on 2023-04-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_tracking', '0022_contentitem_raw_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentItemAutoMarkerConfig',
        ),
    ]
