# Generated by Django 3.1.4 on 2023-07-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('curriculum_tracking', '0023_delete_contentitemautomarkerconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentavailableflavour',
            unique_together={('tag', 'content_item')},
        ),
    ]
