# Generated by Django 3.1.4 on 2024-03-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_tracking', '0024_auto_20230727_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='topic_needs_review',
        ),
    ]
