import type { AppProps } from "next/app";
import Head from "next/head";

import { MantineProvider } from "@mantine/core";
// import { NotificationsProvider } from "@mantine/notifications";
// If we upgrade Mantine to version 6 then the way we do notifications will need to change. ...hmmm. Maybe worth upgrading now acutually

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Coding challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <MantineProvider
        withGlobalStyles
        withNormalizeCSS
        // theme={{ colorScheme: "dark" }}
      >
        {/* <NotificationsProvider> */}
        <Component {...pageProps} />
        {/* </NotificationsProvider> */}
      </MantineProvider>
    </>
  );
}
