apiVersion: apps/v1

kind: Deployment
metadata:
  name: automarker
  labels:
    app: automarker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: automarker
  template:
    metadata:
      labels:
        app: automarker
    spec:
      containers:
        - name: automarker-app
          image: gcr.io/umuzi-prod/automarker:latest 
          imagePullPolicy: Always
          
          ports:
            - containerPort: 1337

          readinessProbe:
            # an http probe
            httpGet:
              path: /health-check
              port: 1337
            initialDelaySeconds: 5
            timeoutSeconds: 5

          volumeMounts:
            - name: github-ssh-key-secret-volume
              readOnly: true
              mountPath: "/root/.ssh"

      volumes:
      - name: github-ssh-key-secret-volume
        secret:
          secretName: github-ssh-key-secret
          defaultMode: 0400
