# Generated by Django 2.1.5 on 2020-09-20 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_leave', models.CharField(choices=[('1', 'Annual Leave'), ('2', 'Sick Leave'), ('3', 'Family Responsibility'), ('4', 'Maternity Leave'), ('5', 'Paternity Leave')], max_length=1)),
                ('reason_for_leave', models.TextField(blank=True, null=True)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('amount_of_days', models.SmallIntegerField(null=True)),
                ('manager', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='leave_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, model_mixins.Mixins),
        ),
    ]
