# Statuses for different project configs

STATUS_DEBUG = "DEBUG"
STATUS_PRODUCTION = "PRODUCTION"
STATUS_DEACTIVATED = "DEACTIVATED"
STATUS_NOT_IMPLEMENTED = "NOT_IMPLEMENTED"

ALLOWED_STATUSES = [
    STATUS_DEBUG,
    STATUS_PRODUCTION,
    STATUS_DEACTIVATED,
    STATUS_NOT_IMPLEMENTED,
]
