export default {
  INITIALISE_GOOGLE_AUTH_START: "INITIALISE_GOOGLE_AUTH_START",
  INITIALISE_GOOGLE_AUTH_SUCCESS: "INITIALISE_GOOGLE_AUTH_SUCCESS",
  INITIALISE_GOOGLE_AUTH_ERROR: "INITIALISE_GOOGLE_AUTH_ERROR",

  //   LOGIN_WITH_GOOGLE_BUTTON_CLICK: "LOGIN_WITH_GOOGLE_BUTTON_CLICK",
};
