# Generated by Django 3.1.4 on 2024-04-17 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_stream_flavours'),
        ('selection_bootcamps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
