# Generated by Django 3.1.4 on 2024-03-27 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_mixins
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('event_copy', models.TextField()),
                ('event_title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_title_text', models.CharField(blank=True, max_length=128, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(related_name='attended_sessions', to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facilitated_sessions', to=settings.AUTH_USER_MODEL)),
                ('flavours', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('guest_facilitators', models.ManyToManyField(blank=True, related_name='guest_facilitated_sessions', to=settings.AUTH_USER_MODEL)),
                ('related_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='session_scheduling.sessiontype')),
            ],
            bases=(models.Model, model_mixins.FlavourMixin),
        ),
    ]
