# Generated by Django 3.1.4 on 2024-04-12 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session_scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(limit_choices_to={'active': True}, related_name='attended_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='facilitator',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facilitated_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='guest_facilitators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, related_name='guest_facilitated_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
