# Generated by Django 3.1.4 on 2024-04-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_scheduling', '0002_auto_20240412_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
