# Generated by Django 3.1.4 on 2024-06-03 10:04

from django.db import migrations, models
import django.db.models.deletion
import model_mixins
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('curriculum_tracking', '0025_remove_contentitem_topic_needs_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReviewPricingScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('weight_share', models.FloatField(blank=True, null=True)),
                ('project_review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_score', to='curriculum_tracking.recruitprojectreview')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReviewAgileWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField()),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum_tracking.contentitem')),
                ('flavours', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            bases=(models.Model, model_mixins.FlavourMixin),
        ),
    ]
