# Generated by Django 2.1.5 on 2020-06-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200528_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohort',
            old_name='extra_label',
            new_name='label',
        ),
    ]
