# Generated by Django 2.1.5 on 2020-08-28 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200701_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('organisation_type', models.CharField(choices=[('SC', 'School'), ('SP', 'EP')], max_length=1)),
            ],
            bases=(models.Model, model_mixins.Mixins),
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_recruit',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='kind',
        ),
        migrations.AddField(
            model_name='user',
            name='is_reviewer',
            field=models.BooleanField(default=False, verbose_name='is reviewer'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='is student'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_trusted_reviewer',
            field=models.BooleanField(default=False, verbose_name='is trusted reviewer'),
        ),
        migrations.AddField(
            model_name='usergroupmembership',
            name='permission_manage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroupmembership',
            name='permission_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroupmembership',
            name='permission_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usergroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='core.UserGroup'),
        ),
        migrations.AlterField(
            model_name='usergroupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usergroupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.AddField(
            model_name='usergroup',
            name='school_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Organisation'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='sponsor_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_user_groups', to='core.Organisation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Organisation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sponsor_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_user_profiles', to='core.Organisation'),
        ),
    ]
