# Generated by Django 2.1.5 on 2020-09-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200828_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_type',
            field=models.CharField(choices=[('S', 'School'), ('E', 'Employer Partner')], max_length=1),
        ),
    ]
