# Generated by Django 3.1.4 on 2021-01-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210121_0230'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergroupmembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usergroupmembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergroupmembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.DeleteModel(
            name='UserGroupMembership',
        ),
    ]
