# Generated by Django 3.1.4 on 2021-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210122_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='short_name',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='url',
            field=models.URLField(blank=True, max_length=2083, null=True, unique=True),
        ),
    ]
