# Generated by Django 3.1.4 on 2021-09-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210528_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
