# Generated by Django 3.1.4 on 2021-11-10 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210922_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StreamRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg: Cohort 30', max_length=100)),
                ('start_date', models.DateField()),
                ('ideal_end_date', models.DateField(blank=True, null=True)),
                ('latest_end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('employer_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.organisation')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curriculum')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stream')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('stream', 'curriculum')},
            },
        ),
    ]
