# Generated by Django 3.1.4 on 2022-06-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_stream_streamcurriculum_streamregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamcurriculum',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_curriculums', to='core.curriculum'),
        ),
        migrations.AlterField(
            model_name='streamcurriculum',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_curriculums', to='core.stream'),
        ),
    ]
