# Generated by Django 3.1.4 on 2023-03-09 08:38

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('core', '0013_auto_20220626_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='team',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
