# Generated by Django 3.1.4 on 2024-03-27 11:00

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('core', '0014_auto_20230309_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='flavours',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
