# Generated by Django 3.1.4 on 2024-04-12 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoderbyteTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_link', models.URLField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Time expired', 'Time expired'), ('In progress', 'In progress'), ('Invited', 'Invited')], max_length=12)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('date_invited', models.DateField(blank=True, null=True)),
                ('assessment_name', models.CharField(max_length=100)),
                ('assessment_id', models.CharField(max_length=100)),
                ('plagiarism', models.CharField(blank=True, choices=[('Likely', 'Likely'), ('Not detected', 'Not detected'), ('Detected', 'Detected')], max_length=13, null=True)),
                ('time_taken_minutes', models.IntegerField(blank=True, null=True)),
                ('challenges_completed', models.IntegerField(blank=True, null=True)),
                ('challenge_score', models.IntegerField(blank=True, null=True)),
                ('multiple_choice_score', models.IntegerField(blank=True, null=True)),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
