#!/bin/sh


echo "CERTBOT_DOMAIN: $CERTBOT_DOMAIN" > certbot.out
echo "CERTBOT_VALIDATION: $CERTBOT_VALIDATION" >> certbot.out
echo "CERTBOT_TOKEN: $CERTBOT_TOKEN" >> certbot.out
echo "CERTBOT_REMAINING_CHALLENGES: $CERTBOT_REMAINING_CHALLENGES" >> certbot.out
echo "CERTBOT_ALL_DOMAINS: $CERTBOT_ALL_DOMAINS" >> certbot.out

sleep 120 
